### Crete a new report
POST localhost:3000/reports
Content-Type: application/json

{
  "price": 150000,
  "make": "audi",
  "model": "a4",
  "year": 2010,
  "latitude": 46.5333,
  "longitude": 6.5833,
  "mileage": 30000
}

### Approve a report
PATCH localhost:3000/reports/1/approve
Content-Type: application/json

{
  "approved": true
}

### Get an estimate of a vehicle
GET localhost:3000/reports/estimate?make=audi&model=a4&year=2010&mileage=50000&latitude=46.5333&longitude=6.5833
